### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by jeudy** [gsalvatori/tredify#5]
Any plans to use it to show animations? (if not, I can contribute).

**Comment by gsalvatori** [comment]
Hi jeudy!

Exactly, what did you mean with "animations"? Beside this, any contribution to the project is more than interesting. :)

**Comment by jeudycecropia** [comment]
Hi,

I mean, animations done with import matplotlib.animation as animation. I'd be awesome to be able to visualize animations from json data. Was that part of your plans?

**Comment by gsalvatori** [comment]
That wasn't in my current plans, but the feature is interesting. Actually I'm working to expand the project, to support GIS/geojson data and it's taking me a long time. So if you can work on animations, I would be grateful. :)

**Comment by jeudy** [comment]
Ok cool, I'll get to it then. I'll fork the repo this weekend and play with it a little.

**Comment by gsalvatori** [comment]
Perfect! Thank you so much

**Comment by gsalvatori** [comment]
Any news?

**Comment by jeudy** [comment]
Work in progress. I'm finishing up my semester, so on the 1st week of
December I'll dedicate more time to it. But definitely will happen.

On Wed, Nov 18, 2015 at 2:16 PM, Gabriele Salvatori <
notifications@github.com> wrote:

> Any news?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gsalvatori/tredify/issues/5#issuecomment-157849282.

## 

---

Jeudy Blanco
_http://www.tuanisapps.com http://www.tuanisapps.com_ - Hybrid Mobile
development freelance services

**Comment by gsalvatori** [comment]
No problem. Thank you! :)

**Comment by jeudy** [comment]
Just submitted a pull request.

There are conflicts because of some PEP8 fixes I made to the existing code
regarding tabs (its recommended to use 4 spaces).

The changes are in a branch called animation. There is a sample json file
with sequence data, you can call it with:

python tredify.py -t animation -i json/sun_earth_jupiter.json -d 3D -v gui

or

python tredify.py -t animation -i json/sun_earth_jupiter.json -d 2D -v gui

Check it out and let me know if you have questions or suggestions.

On Wed, Nov 18, 2015 at 2:50 PM, Gabriele Salvatori <
notifications@github.com> wrote:

> No problem. Thank you! :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gsalvatori/tredify/issues/5#issuecomment-157859463.

## 

---

Jeudy Blanco
_http://www.tuanisapps.com http://www.tuanisapps.com_ - Hybrid Mobile
development freelance services

**Comment by gsalvatori** [comment]
Hi!

is this branch aligned with the latest development changes? Make sure of this because that's a massive pull request. In addition to that, I think we should keep only a minor part of all the test files. Btw thanks for the new features and tomorrow I'll test the code :)

**Comment by jeudy** [comment]
Hi Gabriele,

Yes, I just made sure I'm up to date with the latest development:

[image: Inline image 1]

The pull request looks huge because of the sample data files I added, but
the actual code is mostly new stuff (what I added for the animation part)
and a few spaces/tabs fixes. The only "major" change to the tredify.py main
file is this:

[image: Inline image 2]

because I converted the lib folder into a proper module:

[image: Inline image 3]

the rest is unchanged.

Take a look at the actual code change and let me know if you think
something is wrong (and also, give it a try to the -t animation option and
let me know what you think).

In the future, I can add more customization to the animation.

On Mon, Nov 30, 2015 at 5:40 PM, Gabriele Salvatori <
notifications@github.com> wrote:

> Hi!
> 
> is this branch aligned with the latest development changes? Make sure of
> this because that's a massive pull request
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gsalvatori/tredify/issues/5#issuecomment-160799615.

## 

---

Jeudy Blanco
_http://www.tuanisapps.com http://www.tuanisapps.com_ - Hybrid Mobile
development freelance services

**Comment by gsalvatori** [comment]
Perfect, today I'll test the code and I'll let you know. Thanks again for this great enhancement :)

**Comment by gsalvatori** [comment]
Ok Jeudy, I merged the pull requests. There were some conflicts also with the GIS functionality but I resolved it. Thanks again for this new features! And for the future, please consider the following guidelines:
- The origin of the pull requests must be **development**
- Make more pull request with minor changes in order to make tests more easy
- Create new features and fixes and not refactoring / code style changes

**Comment by jeudy** [comment]
Excellent, and yes, I'll follow these guidelines for future enhancements
(I'll be adding some extra samples for animation and some customization to
the plots).

Thanks

On Tue, Dec 1, 2015 at 3:22 AM, Gabriele Salvatori <notifications@github.com

> wrote:
> 
> Ok Jeudy, I merged the pull requests. There were some conflicts also with
> the GIS functionality but I resolved it. Thanks again for this new
> features! And for the future, please consider the following guidelines:
> - The origin of the pull requests must be _development_
> - Make more pull request with minor changes in order to make tests
>   more easy
> - Create new features and fixes and not refactoring / code style
>   changes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gsalvatori/tredify/issues/5#issuecomment-160905348.

## 

---

Jeudy Blanco
_http://www.tuanisapps.com http://www.tuanisapps.com_ - Hybrid Mobile
development freelance services

**Comment by gsalvatori** [comment]
Perfect, thank you so much!
